[SITE] Guest post for fail2ban setup
apache/james-project pull request #1599
Opened 2023-06-20 07:48 UTC by chibenwa

2023-06-21 03:22 UTC, Arsnael approved these changes
Few small typos but looks great to me, very instructive :)

Thanks to Paul Gunter for writing this up!

2023-06-21 03:22 UTC, Arsnael commented on src/homepage/_posts/2023-06-20-fail2ban.markdown
> +# Repel brute force attackes with Linux firewall (iptables) and fail2ban
```suggestion
# Repel brute force attacks with Linux firewall (iptables) and fail2ban
```

2023-06-21 03:22 UTC, Arsnael commented on src/homepage/_posts/2023-06-20-fail2ban.markdown
> +Ubuntu installs the software. After start fail3ban manually. Finally the service is set to start
```suggestion
Ubuntu installs the software. After start fail2ban manually. Finally the service is set to start
```

2023-06-21 03:22 UTC, Arsnael commented on src/homepage/_posts/2023-06-20-fail2ban.markdown
> + -
```suggestion

```

2023-06-21 09:18 UTC, quantranhong1999 approved these changes
Interesting article.

2023-06-21 09:45 UTC, Arsnael approved these changes

2023-06-21 09:47 UTC, vttranlina approved these changes

2023-06-21 12:11 UTC, guenterpaul requested changes
some lines are text - not code

2023-06-21 12:11 UTC, guenterpaul commented on src/homepage/_posts/2023-06-20-fail2ban.markdown
> +In our case we change the values only for the SSHD service in the „/etc/fail2ban/jail.d/defaultsdebian.conf“ file. After the file looks like this:
This is Text, co code

2023-06-21 12:11 UTC, guenterpaul commented on src/homepage/_posts/2023-06-20-fail2ban.markdown
> +We see 2 regular expressions there. The first looks at the „AbstractValidRcptHandler“ class. The IP
This and the next 4 lines are text, no code

2023-06-22 05:42 UTC, chibenwa commented on src/homepage/_posts/2023-06-20-fail2ban.markdown
> +[sshd]
```suggestion
maxretry = 5
```

In our case we change the values only for the SSHD service in the „/etc/fail2ban/jail.d/defaultsdebian.conf“ file. After the file looks like this:

```
[sshd]
```

2023-06-22 05:43 UTC, chibenwa commented on src/homepage/_posts/2023-06-20-fail2ban.markdown
> +[james]
````suggestion
ignoreregex =
```
We see 2 regular expressions there. The first looks at the „AbstractValidRcptHandler“ class. The IP
address is filled via the James variable. The IP address is recognized with the placeholder <HOST>.

The second looks at the "AuthCmdHandler" class, the IP address is at the end of the line.

## Setup Jail

We create the file "/etc/fail2ban/jail.d/james.conf" with the following content:
```
[james]
````

2023-06-22 06:29 UTC, guenterpaul commented
@chibenwa Thanks a lot for changes. There are still some problems with line breaks and spaces. I think my PDF file was the problem. The files are "log4j2.xml", "james.log" and "james.conf". There are the lines:  
[code.txt](https://github.com/apache/james-project/files/11829586/code.txt)

2023-06-27 05:16 UTC, merged