JAMES-3925 - JMAP Upload - cleanup/fixup/optimize upload usage
apache/james-project pull request #2069
Opened 2024-02-29 03:20 UTC by vttranlina

2024-02-29 04:18 UTC, hungphan227 approved these changes

2024-02-29 04:40 UTC, quantranhong1999 approved these changes

2024-02-29 07:15 UTC, Arsnael approved these changes

2024-02-29 07:42 UTC, chibenwa commented on server/data/data-jmap/src/test/java/org/apache/james/jmap/api/upload/UploadRepositoryContract.scala
> +   @Test
Missing LF

2024-02-29 07:42 UTC, chibenwa commented on server/data/data-jmap-cassandra/src/main/java/org/apache/james/jmap/cassandra/upload/UploadDAO.java
> +            .ifExists()
Using a LWT? Are we sure we need strong consistency?

2024-02-29 07:43 UTC, chibenwa requested changes
Using LWTs is a nogo for me.

2024-02-29 14:39 UTC, chibenwa approved these changes

2024-03-01 09:20 UTC, Arsnael commented
Can you squash the fixup @vttranlina ?

2024-03-01 09:30 UTC, vttranlina commented
squash fixup

2024-03-04 03:32 UTC, merged