[FIX] JMAP: Only log ERROR for `serverFail` errors
apache/james-project pull request #2220
Opened 2024-04-29 05:51 UTC by quantranhong1999

IMO we should not log user input errors.

Or @chibenwa do you want to keep the `RequestTooLargeException` log for example?

2024-04-29 08:17 UTC, chibenwa requested changes
Reviewing this I think all those user input related errors would deserved to be info logged, so for `RequestTooLargeException`  but also `IdentityIdNotFoundException`, `ChangeNotFoundException`, `MailboxNotFoundException`, `IllegalArgumentException`, `UnsupportedNestingException`, `UnsupportedFilterException`, `UnsupportedSortException`, `UnsupportedRequestParameterException`, `ForbiddenAccountManagementException`, `AccountNotFoundException`...

Loosing this valuable debugging exception feels like a waste while clearly ERROR logging is overkill...

2024-05-02 02:56 UTC, quantranhong1999 commented
I reworked the changes.

2024-05-02 04:04 UTC, Arsnael approved these changes

2024-05-02 06:51 UTC, vttranlina reviewed
read it

2024-05-02 07:05 UTC, chibenwa approved these changes

2024-05-02 07:09 UTC, merged