JAMES-4083 remove logback jackson usages from james
apache/james-project pull request #2482
Opened 2024-10-31 15:35 UTC by florentos17

cf the [jira ticket](https://issues.apache.org/jira/browse/JAMES-4083)

i mounted the jar files as suggested, but i could not manage to point to them in every pom file. using ${project.basedir} in the parent pom does not work since it points to each pom's individual base directory... should i specify the path in each pom ?

2024-11-18 07:51 UTC, chibenwa commented
```
[WARNING] 'dependencyManagement.dependencies.dependency.systemPath' for ch.qos.logback.contrib:logback-jackson:jar should not point at files within the project directory, ${project.basedir}/root/libs/logback-jackson-0.1.5.jar will be unresolvable by dependent projects @ line 2082, column 29
[WARNING] 'dependencyManagement.dependencies.dependency.systemPath' for ch.qos.logback.contrib:logback-json-classic:jar should not point at files within the project directory, ${project.basedir}/root/libs/logback-jackson-classic-0.1.5.jar will be unresolvable by dependent projects @ line 2089, column 29
[WARNING] 'dependencyManagement.dependencies.dependency.systemPath' for ch.qos.logback.contrib:logback-json-classic:jar refers to a non-existing file /home/jenkins/workspace/james_ApacheJames_PR-2482/root/libs/logback-jackson-classic-0.1.5.jar @ line 2089, column 29
```

@florentos17  this PR is opened for over 2 weeks and failures are clearly related.

Please take some time on it!

2024-11-18 14:13 UTC, chibenwa requested changes

2024-11-18 14:13 UTC, chibenwa commented on pom.xml
> +                <systemPath>${project.basedir}/root/libs/logback-jackson-0.1.5.jar</systemPath>
Remove to not mean add the linagora specific lib as a magic jar depedency.

BTW binary is not reviewable source code and do not meet ASF standards.

2024-11-21 09:54 UTC, florentos17 commented
so the tests failing are all of those from the class `james-project/third-party/crowdsec/src/test/java/org/apache/james/crowdsec/CrowdsecIntegrationTest.java`

i run those locally and they passed without a problem...!

2024-11-21 11:44 UTC, chibenwa commented
rebase?

2024-11-22 03:26 UTC, Arsnael approved these changes

2024-11-22 14:22 UTC, chibenwa commented
And update the lockat files to remove mentions of Json encoders.

2024-11-25 20:00 UTC, chibenwa commented
This indeed is more fundamental.

Crowdsec extension as it exists relies on structured logging.

CF https://github.com/apache/james-project/blob/fa5f1c8484901fad629a13cb209c515717e7489a/third-party/crowdsec/sample-configuration/parsers/syslog-logs.yaml#L40

My proposal would be to:

 - Add logback-json back as a provided dependency of `third-party/crowdsec`
 - And document how to mount in runtime the `logback-json` file onto the classpath.

2024-11-26 10:29 UTC, chibenwa commented on third-party/crowdsec/README.md
> +- Mount the configuration file onto the classpath
How to do this?

2024-11-26 12:49 UTC, chibenwa approved these changes

2024-11-27 10:06 UTC, chibenwa commented
(already done) 

https://github.com/linagora/tmail-backend/pull/1333

2024-11-27 14:06 UTC, merged